#!/bin/sh
set -eu

uci -q batch <<'UCIEOF'
delete ucitrack.@proxypool[-1]
add ucitrack proxypool
set ucitrack.@proxypool[-1].init='proxypool'
commit ucitrack
UCIEOF

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache

exit 0
