#!/bin/sh
# 智联盒子 - DNS 代理管理脚本
# 通过 dnscrypt-proxy2 将 DNS 查询路由到 SLP SOCKS5 隧道，彻底绕过 DNS 污染
#
# 链路: dnsmasq(:53) → dnscrypt-proxy2(:5335) → SOCKS5(:SLP端口) → SLP隧道 → Google/Cloudflare DoH

DNS_CONF="/etc/dnscrypt-proxy2/dnscrypt-proxy.toml"
DNS_LISTEN_PORT=5335
RUN_DIR="/var/run/proxypool"
DNS_PORT_FILE="$RUN_DIR/dns-proxy-port"
LOG_FILE="/var/log/proxypool.log"

log_info() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [dns] $*" >> "$LOG_FILE"
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [dns] [ERROR] $*" >> "$LOG_FILE"
}

# 查找第一个存活的 SLP 客户端 SOCKS5 端口
find_socks5_port() {
    local slp_dir="$RUN_DIR/slp"
    for client_dir in "$slp_dir"/*/; do
        [ -d "$client_dir" ] || continue
        local pid_file="${client_dir}slp.pid"
        local port_file="${client_dir}socks5.port"
        if [ -f "$pid_file" ] && [ -f "$port_file" ]; then
            local pid=$(cat "$pid_file")
            if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
                cat "$port_file"
                return 0
            fi
        fi
    done
    return 1
}

# 获取 ISP DNS（用于 dnscrypt-proxy2 bootstrap，仅解析 DoH 服务器域名）
_get_bootstrap_dns() {
    local isp_dns=$(grep -m1 '^nameserver' /tmp/resolv.conf.d/resolv.conf.auto 2>/dev/null | awk '{print $2}')
    echo "${isp_dns:-9.9.9.11}"
}

# 生成 dnscrypt-proxy2 配置文件
_write_config() {
    local socks5_port="$1"
    local bootstrap_dns=$(_get_bootstrap_dns)

    cat > "$DNS_CONF" << EOF
# Auto-generated by proxypool dns-manager
# DNS queries are routed through SLP SOCKS5 tunnel to bypass DNS pollution
# Do NOT edit manually - changes will be overwritten on next client start/stop

server_names = ['google', 'cloudflare']
listen_addresses = ['127.0.0.1:${DNS_LISTEN_PORT}']
max_clients = 250

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false

require_nolog = true
require_nofilter = true

# 强制 TCP：SOCKS5 不支持 UDP
force_tcp = true

# DNS 查询通过 SLP SOCKS5 隧道转发
proxy = 'socks5://127.0.0.1:${socks5_port}'

timeout = 5000
keepalive = 30

# Bootstrap DNS：仅用于解析 DoH 服务器域名（直连 ISP DNS，不走代理）
# 用户实际的 DNS 查询不会经过 bootstrap
bootstrap_resolvers = ['${bootstrap_dns}:53']
ignore_system_dns = true

# 跳过网络探测（避免启动延迟）
netprobe_timeout = 0

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

cert_refresh_delay = 240

log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

block_unqualified = true
block_undelegated = true
reject_ttl = 10

[sources]
  [sources.public-resolvers]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    cache_file = 'public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

  [sources.relays]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
    cache_file = 'relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

[query_log]
format = 'tsv'

[nx_log]
format = 'tsv'

[blocked_names]
[blocked_ips]
[allowed_names]
[allowed_ips]
[captive_portals]
[local_doh]
[schedules]
[static]
[anonymized_dns]
[dns64]
[doh_client_x509_auth]
EOF
}

# ============================================================
# 配置 DNS 代理（SLP 客户端启动后调用）
# ============================================================
configure() {
    local socks5_port="$1"

    # 未指定端口则自动查找
    if [ -z "$socks5_port" ]; then
        socks5_port=$(find_socks5_port)
        if [ -z "$socks5_port" ]; then
            log_info "No SLP client available, skipping DNS proxy configuration"
            return 1
        fi
    fi

    # 已配置相同端口则跳过
    if [ -f "$DNS_PORT_FILE" ]; then
        local current_port=$(cat "$DNS_PORT_FILE")
        if [ "$current_port" = "$socks5_port" ]; then
            # 确保 dnscrypt-proxy 进程存活
            if pgrep -x dnscrypt-proxy >/dev/null 2>&1; then
                return 0
            fi
        fi
    fi

    # 检查 dnscrypt-proxy2 是否已安装
    if [ ! -x /usr/sbin/dnscrypt-proxy ]; then
        log_error "dnscrypt-proxy2 not installed, DNS proxy disabled"
        return 1
    fi

    log_info "Configuring DNS proxy: dnsmasq → dnscrypt-proxy2(:$DNS_LISTEN_PORT) → SOCKS5(:$socks5_port) → SLP tunnel"

    # 写入 dnscrypt-proxy2 配置
    _write_config "$socks5_port"
    echo "$socks5_port" > "$DNS_PORT_FILE"

    # 启动/重启 dnscrypt-proxy2
    /etc/init.d/dnscrypt-proxy restart 2>/dev/null
    sleep 2

    # 配置 dnsmasq 使用 dnscrypt-proxy2
    _configure_dnsmasq

    log_info "DNS proxy active"
}

# ============================================================
# 恢复 ISP DNS（proxypool 停止或无 SLP 客户端时调用）
# ============================================================
restore() {
    log_info "Restoring DNS to ISP default"

    # 恢复 dnsmasq 为系统默认 DNS
    _restore_dnsmasq

    # 停止 dnscrypt-proxy2
    /etc/init.d/dnscrypt-proxy stop 2>/dev/null

    rm -f "$DNS_PORT_FILE"
}

# ============================================================
# 检查 DNS 代理状态，必要时切换端口或恢复
# （SLP 客户端断开时调用）
# ============================================================
check() {
    # 未配置过则尝试配置
    if [ ! -f "$DNS_PORT_FILE" ]; then
        configure
        return
    fi

    local current_port=$(cat "$DNS_PORT_FILE")

    # 当前端口仍然存活则无需操作
    if nc -z -w 1 127.0.0.1 "$current_port" >/dev/null 2>&1; then
        return 0
    fi

    # 当前端口失效，寻找替代
    local new_port=$(find_socks5_port)
    if [ -n "$new_port" ]; then
        log_info "DNS proxy switching: port $current_port → $new_port"
        configure "$new_port"
    else
        log_info "No SLP clients available, restoring ISP DNS"
        restore
    fi
}

# ============================================================
# dnsmasq 配置管理
# ============================================================

_configure_dnsmasq() {
    uci set dhcp.@dnsmasq[0].noresolv='1'
    uci delete dhcp.@dnsmasq[0].server 2>/dev/null
    uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#${DNS_LISTEN_PORT}"
    uci commit dhcp
    /etc/init.d/dnsmasq restart 2>/dev/null
}

_restore_dnsmasq() {
    uci set dhcp.@dnsmasq[0].noresolv='0'
    uci delete dhcp.@dnsmasq[0].server 2>/dev/null
    uci commit dhcp
    /etc/init.d/dnsmasq restart 2>/dev/null
}

case "$1" in
    configure)
        configure "$2"
        ;;
    restore)
        restore
        ;;
    check)
        check
        ;;
    *)
        echo "Usage: $0 {configure|restore|check} [socks5_port]"
        exit 1
        ;;
esac
